### ISSUE TITLE
Chargement des polices

### ISSUE THREAD

**Issue by kazerlelutin** [bakakoozin/Zozor#1]
https://github.com/bakakoozin/Zozor/blob/11c18dafea3ad9340701b3d915842a0b5117c8b7/index.html#L14

Est-ce qu'il n'y aura pas une autre façon de charger les polices ?

**Comment by kazerlelutin** [comment]
https://developer.mozilla.org/fr/docs/Web/CSS/@font-face

**Comment by bakakoozin** [comment]
C'est fait. Merci pour le coup de pouce.

**Comment by kazerlelutin** [comment]
![image](https://github.com/bakakoozin/Zozor/assets/79605267/3fe09677-85ca-4e17-ae42-cdb18c0fa939)

fonts

**Comment by kazerlelutin** [comment]
![image](https://github.com/bakakoozin/Zozor/assets/79605267/584ad9dc-7032-41e0-9e84-58e7043d6aaf)

**Comment by bakakoozin** [comment]
je l'ai viré
