### ISSUE TITLE
Create a JS server

### ISSUE THREAD

**Issue by kazerlelutin** [bakakoozin/Zozor#20]
- create a server with https://expressjs.com/fr/
- use .env file for keep secret your api keys
- create a hello word enpoint (send text "hello world" for response)
- display in your frontend the hello world response.

**Comment by bakakoozin** [comment]
pas sûr d'avoir fait ça correctement

**Comment by bakakoozin** [comment]
c'est fait
la réponse du serveur s'affiche dans le h1
