### ISSUE TITLE
builder

### ISSUE THREAD

**Issue by kazerlelutin** [bakakoozin/Zozor#21]
use vite in your projet : 

[Vite](https://vitejs.dev/)

See  : 
[StackBlitz Zoror](https://stackblitz.com/edit/vitejs-vite-51tcv8?file=index.html,package.json,public%2Fstyles%2Fstyle.css,back%2Findex.js,main.js,helpers%2FgetTitle.js&terminal=dev)

 for the next steps
- [x] don't use CLI, install the npm package. 
- [x] install packages (concurrently....)
- [x] organize your code in your projet like exemple
- [x] see how the code is splitted (import for fetch title... )
- [x] test with npm run dev command (insert scripts in package before)
- [x] back run on http://localhost:5000, front http://localhost:5173
- [x] don't open directly index.html to see result, use http://localhost:5173 and see the hot reload.

**Comment by kazerlelutin** [comment]
update description @bakakoozin

**Comment by bakakoozin** [comment]
pour cette partie c'est fait
