### ISSUE TITLE
Séparateur

### ISSUE THREAD

**Issue by kazerlelutin** [bakakoozin/Zozor#6]
https://github.com/bakakoozin/Zozor/blob/11c18dafea3ad9340701b3d915842a0b5117c8b7/index.html#L102C1-L103

2 balises pour gérer ça ?

**Comment by bakakoozin** [comment]
modifié: une seule balise suffit maintenant

**Comment by kazerlelutin** [comment]
https://github.com/bakakoozin/Zozor/blob/811637ad43e1a0709b9f08f4a44797b40b1c067b/style/style.css#L43C1-L49C2

**Comment by bakakoozin** [comment]
j'ai enlevé le "display: flex" qui ne servait à rien
